### ISSUE TITLE
ECEMF implementations

### ISSUE THREAD

**Issue by PhilippMaschi** [H2020-newTRENDs/FLEX#51]
- I was also thinking of maybe somehow reducing the size of the saved data. I added in the ECEMF branch a line of code (pd.to_numeric) in the data_collector which should automatically downscale integers when possible, floats I set to float32 (because I don't think we need the super high precision).. 

- Also I added the possibility to only save certain variables as hourly values to reduce the df size for specific projects (in ECEMF i only need the grid load and 3 other parameters on hourly level). 

- Multiprocessing was added for a single project (project folder is split into subfolders where each scenario table contains a part of the total scenario table)

**Comment by SongminYu** [comment]
I copied these points to the refactor issue and closed this one. I will create a new branch in that issue to implement them. Also, if you have other ideas to be considered in the refactor process, leave a comment there :)
